# Generated by Django 5.1.1 on 2024-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет подложки'),
        ),
    ]
